using Bubblefy.Model;

namespace Bubblefy.Data;

public static class DadosSemente
{
    public static List<Faixa> ObterFaixas()
    {
        return new List<Faixa>
        {
            new Faixa { Id = 1, Titulo = "Night Drive", Artista = "Nova Wave", Genero = "Eletronica", Pais = "EUA", Ano = 2019, BpmMedia = 110, Valencia = 2 },
            new Faixa { Id = 2, Titulo = "Sunset Groove", Artista = "Kalani Reef", Genero = "Eletronica", Pais = "Alemanha", Ano = 2022, BpmMedia = 124, Valencia = 4 },
            new Faixa { Id = 3, Titulo = "Concreto", Artista = "Zona Sul", Genero = "Rap", Pais = "Brasil", Ano = 1997, BpmMedia = 90, Valencia = 1 },
            new Faixa { Id = 4, Titulo = "Chuva de Verao", Artista = "Irene Sa", Genero = "MPB", Pais = "Brasil", Ano = 2015, BpmMedia = 78, Valencia = 4 },
            new Faixa { Id = 5, Titulo = "Static Youth", Artista = "Grey Fields", Genero = "Rock", Pais = "Reino Unido", Ano = 1981, BpmMedia = 132, Valencia = 1 },
            new Faixa { Id = 6, Titulo = "Golden Hour", Artista = "Mira Solt", Genero = "Pop", Pais = "EUA", Ano = 2021, BpmMedia = 96, Valencia = 4 },
            new Faixa { Id = 7, Titulo = "Skank Ferrugem", Artista = "Os Legitimos", Genero = "Reggae", Pais = "Jamaica", Ano = 1968, BpmMedia = 82, Valencia = 3 },
            new Faixa { Id = 8, Titulo = "Underpass", Artista = "Kollektiv Berlin", Genero = "Eletronica", Pais = "Alemanha", Ano = 2018, BpmMedia = 128, Valencia = 1 },
            new Faixa { Id = 9, Titulo = "Aguas de Marco Revisitada", Artista = "Clarice Bittencourt", Genero = "MPB", Pais = "Brasil", Ano = 2020, BpmMedia = 100, Valencia = 3 },
            new Faixa { Id = 10, Titulo = "Neon Hearts", Artista = "Mainline", Genero = "Pop", Pais = "EUA", Ano = 2023, BpmMedia = 118, Valencia = 5 },
            new Faixa { Id = 11, Titulo = "Smoke Signals", Artista = "Delta Horn", Genero = "Jazz", Pais = "EUA", Ano = 1964, BpmMedia = 70, Valencia = 2 },
            new Faixa { Id = 12, Titulo = "Trilha de Serra", Artista = "Vento Norte", Genero = "MPB", Pais = "Brasil", Ano = 2024, BpmMedia = 88, Valencia = 3 },
            new Faixa { Id = 13, Titulo = "Overdrive Nation", Artista = "Steel Kite", Genero = "Rock", Pais = "EUA", Ano = 2013, BpmMedia = 150, Valencia = 1 },
            new Faixa { Id = 14, Titulo = "Ilha Deserta", Artista = "Bruma Costa", Genero = "MPB", Pais = "Brasil", Ano = 2022, BpmMedia = 84, Valencia = 2 },
            new Faixa { Id = 15, Titulo = "Warehouse 4AM", Artista = "Obsidian Loop", Genero = "Eletronica", Pais = "Reino Unido", Ano = 2021, BpmMedia = 140, Valencia = 2 },
            new Faixa { Id = 16, Titulo = "Crystal Echo", Artista = "Polar Lights", Genero = "Pop", Pais = "Canadá", Ano = 2020, BpmMedia = 112, Valencia = 5 },
            new Faixa { Id = 17, Titulo = "Cidade Cinza", Artista = "Rua 9", Genero = "Rap", Pais = "Brasil", Ano = 2018, BpmMedia = 92, Valencia = 2 },
            new Faixa { Id = 18, Titulo = "Midnight Train", Artista = "Blue Rails", Genero = "Blues", Pais = "EUA", Ano = 1994, BpmMedia = 74, Valencia = 2 },
            new Faixa { Id = 19, Titulo = "Aurora Azul", Artista = "Luna Clara", Genero = "Indie", Pais = "Brasil", Ano = 2023, BpmMedia = 108, Valencia = 4 },
            new Faixa { Id = 20, Titulo = "Electric Mirage", Artista = "Circuit Nine", Genero = "Eletronica", Pais = "França", Ano = 2021, BpmMedia = 126, Valencia = 3 },
            new Faixa { Id = 21, Titulo = "Horizonte", Artista = "Campo Aberto", Genero = "Folk", Pais = "Brasil", Ano = 2017, BpmMedia = 80, Valencia = 4 },
            new Faixa { Id = 22, Titulo = "Burning Asphalt", Artista = "Red Motion", Genero = "Rock", Pais = "Austrália", Ano = 2016, BpmMedia = 145, Valencia = 2 },
            new Faixa { Id = 23, Titulo = "Ocean Lights", Artista = "Deep Horizon", Genero = "Pop", Pais = "Nova Zelândia", Ano = 2022, BpmMedia = 104, Valencia = 5 },
            new Faixa { Id = 24, Titulo = "Favela Dreams", Artista = "MC Horizonte", Genero = "Rap", Pais = "Brasil", Ano = 2021, BpmMedia = 95, Valencia = 3 },
            new Faixa { Id = 25, Titulo = "Silent Forest", Artista = "Evergreen", Genero = "Folk", Pais = "Irlanda", Ano = 2012, BpmMedia = 76, Valencia = 4 },
            new Faixa { Id = 26, Titulo = "Solar Pulse", Artista = "Ion Beats", Genero = "Eletronica", Pais = "Holanda", Ano = 2024, BpmMedia = 130, Valencia = 5 },
            new Faixa { Id = 27, Titulo = "Velha Estrada", Artista = "Antonio Leme", Genero = "MPB", Pais = "Brasil", Ano = 2010, BpmMedia = 86, Valencia = 3 },
            new Faixa { Id = 28, Titulo = "Iron Skies", Artista = "Black Avenue", Genero = "Rock", Pais = "EUA", Ano = 2008, BpmMedia = 138, Valencia = 1 },
            new Faixa { Id = 29, Titulo = "Late Coffee", Artista = "Urban Notes", Genero = "Jazz", Pais = "Canadá", Ano = 2019, BpmMedia = 72, Valencia = 4 },
            new Faixa { Id = 30, Titulo = "Northern Wind", Artista = "Snow Valley", Genero = "Indie", Pais = "Noruega", Ano = 2022, BpmMedia = 102, Valencia = 3 },
            new Faixa { Id = 31, Titulo = "Rua das Flores", Artista = "Marina Luz", Genero = "MPB", Pais = "Brasil", Ano = 2016, BpmMedia = 89, Valencia = 5 },
            new Faixa { Id = 32, Titulo = "Voltage", Artista = "Neon Circuit", Genero = "Eletronica", Pais = "Alemanha", Ano = 2023, BpmMedia = 132, Valencia = 4 },
            new Faixa { Id = 33, Titulo = "Broken Compass", Artista = "Atlas", Genero = "Rock", Pais = "Reino Unido", Ano = 2015, BpmMedia = 136, Valencia = 2 },
            new Faixa { Id = 34, Titulo = "Morning Dew", Artista = "Hazel Creek", Genero = "Folk", Pais = "EUA", Ano = 2011, BpmMedia = 78, Valencia = 5 },
            new Faixa { Id = 35, Titulo = "Cidade Neon", Artista = "Lucas Prado", Genero = "Pop", Pais = "Brasil", Ano = 2024, BpmMedia = 116, Valencia = 5 },
            new Faixa { Id = 36, Titulo = "Bass Runner", Artista = "Pulse Engine", Genero = "Eletronica", Pais = "Suécia", Ano = 2020, BpmMedia = 128, Valencia = 2 },
            new Faixa { Id = 37, Titulo = "Black River", Artista = "Old Whiskey", Genero = "Blues", Pais = "EUA", Ano = 1999, BpmMedia = 73, Valencia = 2 },
            new Faixa { Id = 38, Titulo = "Mar Aberto", Artista = "Ana Costa", Genero = "MPB", Pais = "Brasil", Ano = 2021, BpmMedia = 91, Valencia = 4 },
            new Faixa { Id = 39, Titulo = "Skyline", Artista = "North Pulse", Genero = "Pop", Pais = "Canadá", Ano = 2018, BpmMedia = 114, Valencia = 4 },
            new Faixa { Id = 40, Titulo = "Desert Bloom", Artista = "Sand Echo", Genero = "Indie", Pais = "Austrália", Ano = 2017, BpmMedia = 98, Valencia = 3 },
            new Faixa { Id = 41, Titulo = "Velvet Sky", Artista = "Silver Coast", Genero = "Pop", Pais = "EUA", Ano = 2020, BpmMedia = 115, Valencia = 4 },
            new Faixa { Id = 42, Titulo = "Cidade de Vidro", Artista = "Banda Prisma", Genero = "Rock", Pais = "Brasil", Ano = 2019, BpmMedia = 132, Valencia = 2 },
            new Faixa { Id = 43, Titulo = "Deep Horizon", Artista = "Echo Waves", Genero = "Eletronica", Pais = "Alemanha", Ano = 2021, BpmMedia = 126, Valencia = 3 },
            new Faixa { Id = 44, Titulo = "Noite Quente", Artista = "Rafa Nunes", Genero = "MPB", Pais = "Brasil", Ano = 2018, BpmMedia = 90, Valencia = 4 },
            new Faixa { Id = 45, Titulo = "Dusty Roads", Artista = "Wild Prairie", Genero = "Country", Pais = "EUA", Ano = 2014, BpmMedia = 84, Valencia = 3 },
            new Faixa { Id = 46, Titulo = "Electric Rain", Artista = "Voltage One", Genero = "Eletronica", Pais = "França", Ano = 2022, BpmMedia = 128, Valencia = 5 },
            new Faixa { Id = 47, Titulo = "Praia Azul", Artista = "Lia Monteiro", Genero = "MPB", Pais = "Brasil", Ano = 2020, BpmMedia = 86, Valencia = 5 },
            new Faixa { Id = 48, Titulo = "Iron Pulse", Artista = "Heavy State", Genero = "Rock", Pais = "Reino Unido", Ano = 2011, BpmMedia = 148, Valencia = 1 },
            new Faixa { Id = 49, Titulo = "Sunday Coffee", Artista = "The Corner Trio", Genero = "Jazz", Pais = "Canadá", Ano = 2017, BpmMedia = 72, Valencia = 4 },
            new Faixa { Id = 50, Titulo = "Nova Aurora", Artista = "Marina Lopes", Genero = "Pop", Pais = "Brasil", Ano = 2023, BpmMedia = 118, Valencia = 5 },
            new Faixa { Id = 51, Titulo = "Fire Escape", Artista = "City Frames", Genero = "Indie", Pais = "EUA", Ano = 2019, BpmMedia = 108, Valencia = 3 },
            new Faixa { Id = 52, Titulo = "Oceano Azul", Artista = "Costa Viva", Genero = "MPB", Pais = "Brasil", Ano = 2016, BpmMedia = 88, Valencia = 4 },
            new Faixa { Id = 53, Titulo = "Chrome Dreams", Artista = "Neon District", Genero = "Eletronica", Pais = "Alemanha", Ano = 2024, BpmMedia = 130, Valencia = 4 },
            new Faixa { Id = 54, Titulo = "Velha Fotografia", Artista = "Pedro Lima", Genero = "Folk", Pais = "Brasil", Ano = 2013, BpmMedia = 79, Valencia = 3 },
            new Faixa { Id = 55, Titulo = "Runaway Lights", Artista = "Atlas Line", Genero = "Rock", Pais = "Austrália", Ano = 2015, BpmMedia = 140, Valencia = 2 },
            new Faixa { Id = 56, Titulo = "Silver Moon", Artista = "Crystal Shore", Genero = "Pop", Pais = "Canadá", Ano = 2022, BpmMedia = 112, Valencia = 5 },
            new Faixa { Id = 57, Titulo = "Beco Sem Saida", Artista = "MC Eclipse", Genero = "Rap", Pais = "Brasil", Ano = 2021, BpmMedia = 94, Valencia = 2 },
            new Faixa { Id = 58, Titulo = "After Midnight", Artista = "Night Echo", Genero = "Jazz", Pais = "EUA", Ano = 2010, BpmMedia = 69, Valencia = 2 },
            new Faixa { Id = 59, Titulo = "Summer Tide", Artista = "Ocean Breeze", Genero = "Indie", Pais = "Nova Zelândia", Ano = 2020, BpmMedia = 101, Valencia = 4 },
            new Faixa { Id = 60, Titulo = "Horizonte Vermelho", Artista = "Sol Nascente", Genero = "MPB", Pais = "Brasil", Ano = 2022, BpmMedia = 87, Valencia = 4 },
            new Faixa { Id = 61, Titulo = "Digital Love", Artista = "Binary Soul", Genero = "Eletronica", Pais = "Suécia", Ano = 2023, BpmMedia = 127, Valencia = 5 },
            new Faixa { Id = 62, Titulo = "Cold Streets", Artista = "Northern Line", Genero = "Rock", Pais = "Noruega", Ano = 2018, BpmMedia = 134, Valencia = 2 },
            new Faixa { Id = 63, Titulo = "Lua Cheia", Artista = "Helena Dias", Genero = "Pop", Pais = "Brasil", Ano = 2021, BpmMedia = 110, Valencia = 5 },
            new Faixa { Id = 64, Titulo = "Golden Dust", Artista = "Amber Hill", Genero = "Country", Pais = "EUA", Ano = 2016, BpmMedia = 82, Valencia = 3 },
            new Faixa { Id = 65, Titulo = "Invisible City", Artista = "Urban Fiction", Genero = "Indie", Pais = "Reino Unido", Ano = 2019, BpmMedia = 106, Valencia = 3 },
            new Faixa { Id = 66, Titulo = "Brisa do Sul", Artista = "Cecilia Rocha", Genero = "MPB", Pais = "Brasil", Ano = 2024, BpmMedia = 92, Valencia = 5 },
            new Faixa { Id = 67, Titulo = "Frequency X", Artista = "Nova Circuit", Genero = "Eletronica", Pais = "Holanda", Ano = 2022, BpmMedia = 129, Valencia = 3 },
            new Faixa { Id = 68, Titulo = "Old Whiskey", Artista = "Blue Lantern", Genero = "Blues", Pais = "EUA", Ano = 2004, BpmMedia = 75, Valencia = 2 },
            new Faixa { Id = 69, Titulo = "Luzes da Cidade", Artista = "Vitor Alves", Genero = "Pop", Pais = "Brasil", Ano = 2023, BpmMedia = 117, Valencia = 4 },
            new Faixa { Id = 70, Titulo = "Storm Riders", Artista = "Iron Horse", Genero = "Rock", Pais = "Canadá", Ano = 2012, BpmMedia = 144, Valencia = 1 },
            new Faixa { Id = 71, Titulo = "Quiet River", Artista = "Green Valley", Genero = "Folk", Pais = "Irlanda", Ano = 2011, BpmMedia = 77, Valencia = 4 },
            new Faixa { Id = 72, Titulo = "Pulse Machine", Artista = "Digital Form", Genero = "Eletronica", Pais = "Alemanha", Ano = 2024, BpmMedia = 131, Valencia = 4 },
            new Faixa { Id = 73, Titulo = "Entre Ruas", Artista = "Linha Central", Genero = "Rap", Pais = "Brasil", Ano = 2020, BpmMedia = 93, Valencia = 2 },
            new Faixa { Id = 74, Titulo = "Blue Horizon", Artista = "Pacific Lights", Genero = "Pop", Pais = "Austrália", Ano = 2021, BpmMedia = 113, Valencia = 5 },
            new Faixa { Id = 75, Titulo = "Echoes of Time", Artista = "Stone Harbor", Genero = "Rock", Pais = "EUA", Ano = 2017, BpmMedia = 138, Valencia = 2 },
            new Faixa { Id = 76, Titulo = "Vale Verde", Artista = "Joana Campos", Genero = "MPB", Pais = "Brasil", Ano = 2015, BpmMedia = 85, Valencia = 4 },
            new Faixa { Id = 77, Titulo = "Digital Bloom", Artista = "Pixel Dreams", Genero = "Eletronica", Pais = "França", Ano = 2023, BpmMedia = 125, Valencia = 5 },
            new Faixa { Id = 78, Titulo = "Black Smoke", Artista = "Road Kings", Genero = "Rock", Pais = "EUA", Ano = 2009, BpmMedia = 142, Valencia = 1 },
            new Faixa { Id = 79, Titulo = "Morning Light", Artista = "Sunny Coast", Genero = "Indie", Pais = "Canadá", Ano = 2022, BpmMedia = 103, Valencia = 5 },
            new Faixa { Id = 80, Titulo = "Fim de Tarde", Artista = "Clara Horizonte", Genero = "MPB", Pais = "Brasil", Ano = 2024, BpmMedia = 90, Valencia = 4 },
            new Faixa { Id = 81, Titulo = "Neon Skyline", Artista = "Future Avenue", Genero = "Eletronica", Pais = "EUA", Ano = 2022, BpmMedia = 128, Valencia = 5 },
            new Faixa { Id = 82, Titulo = "Rio Sereno", Artista = "Lucas Barreto", Genero = "MPB", Pais = "Brasil", Ano = 2018, BpmMedia = 84, Valencia = 4 },
            new Faixa { Id = 83, Titulo = "Burning Wheels", Artista = "Rust Machine", Genero = "Rock", Pais = "Canadá", Ano = 2015, BpmMedia = 146, Valencia = 2 },
            new Faixa { Id = 84, Titulo = "Open Roads", Artista = "Country Mile", Genero = "Country", Pais = "EUA", Ano = 2017, BpmMedia = 86, Valencia = 3 },
            new Faixa { Id = 85, Titulo = "Cidade Lunar", Artista = "MC Prisma", Genero = "Rap", Pais = "Brasil", Ano = 2021, BpmMedia = 92, Valencia = 2 },
            new Faixa { Id = 86, Titulo = "Crystal Waves", Artista = "Ocean Pulse", Genero = "Eletronica", Pais = "Holanda", Ano = 2023, BpmMedia = 130, Valencia = 4 },
            new Faixa { Id = 87, Titulo = "Velho Piano", Artista = "Henrique Luz", Genero = "Jazz", Pais = "Brasil", Ano = 2014, BpmMedia = 71, Valencia = 3 },
            new Faixa { Id = 88, Titulo = "Skybound", Artista = "North Lights", Genero = "Pop", Pais = "Noruega", Ano = 2020, BpmMedia = 114, Valencia = 5 },
            new Faixa { Id = 89, Titulo = "Iron Heart", Artista = "Steel Nation", Genero = "Rock", Pais = "Reino Unido", Ano = 2012, BpmMedia = 141, Valencia = 1 },
            new Faixa { Id = 90, Titulo = "Mar de Dentro", Artista = "Ana Ribeiro", Genero = "MPB", Pais = "Brasil", Ano = 2024, BpmMedia = 89, Valencia = 5 },
            new Faixa { Id = 91, Titulo = "Shadow Pulse", Artista = "Dark Circuit", Genero = "Eletronica", Pais = "Alemanha", Ano = 2021, BpmMedia = 127, Valencia = 2 },
            new Faixa { Id = 92, Titulo = "Golden Leaves", Artista = "Autumn Hills", Genero = "Folk", Pais = "Irlanda", Ano = 2016, BpmMedia = 79, Valencia = 4 },
            new Faixa { Id = 93, Titulo = "Rua Sem Nome", Artista = "Coletivo Norte", Genero = "Rap", Pais = "Brasil", Ano = 2019, BpmMedia = 95, Valencia = 2 },
            new Faixa { Id = 94, Titulo = "Blue Fire", Artista = "Pacific Echo", Genero = "Pop", Pais = "Austrália", Ano = 2022, BpmMedia = 116, Valencia = 5 },
            new Faixa { Id = 95, Titulo = "Static Dreams", Artista = "Voltage Sky", Genero = "Eletronica", Pais = "Suécia", Ano = 2024, BpmMedia = 129, Valencia = 4 },
            new Faixa { Id = 96, Titulo = "Dust and Steel", Artista = "Highway Sons", Genero = "Rock", Pais = "EUA", Ano = 2013, BpmMedia = 143, Valencia = 2 },
            new Faixa { Id = 97, Titulo = "Canção da Serra", Artista = "Marcos Vidal", Genero = "MPB", Pais = "Brasil", Ano = 2017, BpmMedia = 87, Valencia = 4 },
            new Faixa { Id = 98, Titulo = "Late Reflections", Artista = "Coffee Quartet", Genero = "Jazz", Pais = "Canadá", Ano = 2018, BpmMedia = 73, Valencia = 3 },
            new Faixa { Id = 99, Titulo = "City Escape", Artista = "Urban Lights", Genero = "Indie", Pais = "EUA", Ano = 2020, BpmMedia = 105, Valencia = 4 },
            new Faixa { Id = 100, Titulo = "Aurora Tropical", Artista = "Bella Costa", Genero = "Pop", Pais = "Brasil", Ano = 2023, BpmMedia = 118, Valencia = 5 },
            new Faixa { Id = 101, Titulo = "Frozen Echo", Artista = "Polar Sound", Genero = "Eletronica", Pais = "Finlândia", Ano = 2022, BpmMedia = 126, Valencia = 3 },
            new Faixa { Id = 102, Titulo = "Heartland", Artista = "Dust Riders", Genero = "Country", Pais = "EUA", Ano = 2015, BpmMedia = 83, Valencia = 4 },
            new Faixa { Id = 103, Titulo = "Além do Mar", Artista = "Catarina Alves", Genero = "MPB", Pais = "Brasil", Ano = 2021, BpmMedia = 91, Valencia = 5 },
            new Faixa { Id = 104, Titulo = "Night Frequency", Artista = "Digital Motion", Genero = "Eletronica", Pais = "França", Ano = 2023, BpmMedia = 132, Valencia = 4 },
            new Faixa { Id = 105, Titulo = "Broken Mirrors", Artista = "Last Avenue", Genero = "Rock", Pais = "Canadá", Ano = 2016, BpmMedia = 137, Valencia = 2 },
            new Faixa { Id = 106, Titulo = "Brilho do Sol", Artista = "Fernanda Luz", Genero = "Pop", Pais = "Brasil", Ano = 2024, BpmMedia = 117, Valencia = 5 },
            new Faixa { Id = 107, Titulo = "Electric Souls", Artista = "Synth Vision", Genero = "Eletronica", Pais = "Alemanha", Ano = 2020, BpmMedia = 124, Valencia = 4 },
            new Faixa { Id = 108, Titulo = "Velvet Rain", Artista = "Moon Harbor", Genero = "Indie", Pais = "Reino Unido", Ano = 2019, BpmMedia = 102, Valencia = 4 },
            new Faixa { Id = 109, Titulo = "Asfalto Quente", Artista = "Linha Vermelha", Genero = "Rap", Pais = "Brasil", Ano = 2022, BpmMedia = 96, Valencia = 2 },
            new Faixa { Id = 110, Titulo = "Blue Lantern", Artista = "Old River Band", Genero = "Blues", Pais = "EUA", Ano = 2011, BpmMedia = 74, Valencia = 3 },
            new Faixa { Id = 111, Titulo = "Summer Echo", Artista = "Coastline", Genero = "Pop", Pais = "Austrália", Ano = 2021, BpmMedia = 111, Valencia = 5 },
            new Faixa { Id = 112, Titulo = "Vale Encantado", Artista = "Pedro Nogueira", Genero = "Folk", Pais = "Brasil", Ano = 2018, BpmMedia = 81, Valencia = 4 },
            new Faixa { Id = 113, Titulo = "Hyperdrive", Artista = "Neon Core", Genero = "Eletronica", Pais = "Japão", Ano = 2024, BpmMedia = 134, Valencia = 5 },
            new Faixa { Id = 114, Titulo = "Stone River", Artista = "Granite Road", Genero = "Rock", Pais = "EUA", Ano = 2010, BpmMedia = 145, Valencia = 1 },
            new Faixa { Id = 115, Titulo = "No Horizonte", Artista = "Elisa Campos", Genero = "MPB", Pais = "Brasil", Ano = 2022, BpmMedia = 88, Valencia = 5 },
            new Faixa { Id = 116, Titulo = "Afterglow", Artista = "Sunset Dreams", Genero = "Pop", Pais = "Canadá", Ano = 2023, BpmMedia = 119, Valencia = 5 },
            new Faixa { Id = 117, Titulo = "Metro Lines", Artista = "City Noise", Genero = "Indie", Pais = "Reino Unido", Ano = 2020, BpmMedia = 107, Valencia = 3 },
            new Faixa { Id = 118, Titulo = "Infinite Motion", Artista = "Pulse Reactor", Genero = "Eletronica", Pais = "Holanda", Ano = 2021, BpmMedia = 128, Valencia = 4 },
            new Faixa { Id = 119, Titulo = "Última Estação", Artista = "Bruno Silveira", Genero = "MPB", Pais = "Brasil", Ano = 2019, BpmMedia = 90, Valencia = 4 },
            new Faixa { Id = 120, Titulo = "Final Sunrise", Artista = "Aurora Project", Genero = "Pop", Pais = "EUA", Ano = 2024, BpmMedia = 120, Valencia = 5 },
            new Faixa { Id = 121, Titulo = "Circuito Paulista", Artista = "Pulso Urbano", Genero = "Eletronica", Pais = "Brasil", Ano = 2024, BpmMedia = 128, Valencia = 4 },
            new Faixa { Id = 122, Titulo = "Praia Digital", Artista = "Costa Sintetica", Genero = "Eletronica", Pais = "Brasil", Ano = 2022, BpmMedia = 124, Valencia = 5 },
            new Faixa { Id = 123, Titulo = "Linha Vermelha", Artista = "Metro Beat", Genero = "Eletronica", Pais = "Brasil", Ano = 2020, BpmMedia = 130, Valencia = 2 },
            new Faixa { Id = 124, Titulo = "Noite em Copacabana", Artista = "DJ Aurora", Genero = "Eletronica", Pais = "Brasil", Ano = 2023, BpmMedia = 122, Valencia = 5 },
            new Faixa { Id = 125, Titulo = "Jazz na Lapa", Artista = "Quarteto Carioca", Genero = "Jazz", Pais = "Brasil", Ano = 2019, BpmMedia = 72, Valencia = 4 },
            new Faixa { Id = 126, Titulo = "Sax Paulista", Artista = "Blue Avenida", Genero = "Jazz", Pais = "Brasil", Ano = 2016, BpmMedia = 69, Valencia = 3 },
            new Faixa { Id = 127, Titulo = "Velho Boteco", Artista = "Os Noturnos", Genero = "Blues", Pais = "Brasil", Ano = 2018, BpmMedia = 74, Valencia = 2 },
            new Faixa { Id = 128, Titulo = "Chuva e Whisky", Artista = "Estrada Azul", Genero = "Blues", Pais = "Brasil", Ano = 2021, BpmMedia = 71, Valencia = 3 },
            new Faixa { Id = 129, Titulo = "Estrada de Terra", Artista = "Sertao Highway", Genero = "Country", Pais = "Brasil", Ano = 2015, BpmMedia = 84, Valencia = 4 },
            new Faixa { Id = 130, Titulo = "Rancho do Sul", Artista = "Campos Abertos", Genero = "Country", Pais = "Brasil", Ano = 2022, BpmMedia = 88, Valencia = 5 },
            new Faixa { Id = 131, Titulo = "Reggae da Ilha", Artista = "Sol do Norte", Genero = "Reggae", Pais = "Brasil", Ano = 2020, BpmMedia = 80, Valencia = 5 },
            new Faixa { Id = 132, Titulo = "Maré Positiva", Artista = "Vibração Livre", Genero = "Reggae", Pais = "Brasil", Ano = 2024, BpmMedia = 82, Valencia = 4 },
            new Faixa { Id = 133, Titulo = "Berlin Stones", Artista = "Kraft Union", Genero = "Rock", Pais = "Alemanha", Ano = 2014, BpmMedia = 140, Valencia = 2 },
            new Faixa { Id = 134, Titulo = "Concrete Noise", Artista = "Autobahn", Genero = "Rock", Pais = "Alemanha", Ano = 2017, BpmMedia = 146, Valencia = 1 },
            new Faixa { Id = 135, Titulo = "Frankfurt Flow", Artista = "MC Kaiser", Genero = "Rap", Pais = "Alemanha", Ano = 2021, BpmMedia = 94, Valencia = 2 },
            new Faixa { Id = 136, Titulo = "Rua de Lisboa", Artista = "Miguel Costa", Genero = "MPB", Pais = "Portugal", Ano = 2023, BpmMedia = 92, Valencia = 4 },
            new Faixa { Id = 137, Titulo = "Tejo Azul", Artista = "Helena Mar", Genero = "MPB", Pais = "Portugal", Ano = 2019, BpmMedia = 86, Valencia = 5 },
            new Faixa { Id = 138, Titulo = "Ciudad del Sol", Artista = "Valeria Luna", Genero = "Pop", Pais = "México", Ano = 2022, BpmMedia = 116, Valencia = 5 },
            new Faixa { Id = 139, Titulo = "Neon Tokyo", Artista = "Haru Sky", Genero = "Indie", Pais = "Japão", Ano = 2024, BpmMedia = 108, Valencia = 4 },
            new Faixa { Id = 140, Titulo = "Monte Azul", Artista = "Los Andes", Genero = "Folk", Pais = "Argentina", Ano = 2017, BpmMedia = 78, Valencia = 4 },
            new Faixa { Id = 141, Titulo = "Shibuya Lights", Artista = "Akira Pulse", Genero = "Eletronica", Pais = "Japão", Ano = 2024, BpmMedia = 132, Valencia = 5 },
            new Faixa { Id = 142, Titulo = "Kyoto Dreams", Artista = "Neon Sakura", Genero = "Eletronica", Pais = "Japão", Ano = 2021, BpmMedia = 126, Valencia = 3 },
            new Faixa { Id = 143, Titulo = "Paris Underground", Artista = "Rouge Signal", Genero = "Rock", Pais = "França", Ano = 2016, BpmMedia = 138, Valencia = 2 },
            new Faixa { Id = 144, Titulo = "Cafe de Nuit", Artista = "Le Quartet", Genero = "Jazz", Pais = "França", Ano = 2015, BpmMedia = 70, Valencia = 3 },
            new Faixa { Id = 145, Titulo = "London Rain", Artista = "Blue Thames", Genero = "Blues", Pais = "Reino Unido", Ano = 2012, BpmMedia = 73, Valencia = 2 },
            new Faixa { Id = 146, Titulo = "Outback Sunset", Artista = "Dust Riders", Genero = "Country", Pais = "Austrália", Ano = 2020, BpmMedia = 86, Valencia = 4 },
            new Faixa { Id = 147, Titulo = "Bogotá Sun", Artista = "Raices Verdes", Genero = "Reggae", Pais = "Colômbia", Ano = 2023, BpmMedia = 81, Valencia = 5 },
            new Faixa { Id = 148, Titulo = "Lisboa Flow", Artista = "Rima Atlântica", Genero = "Rap", Pais = "Portugal", Ano = 2022, BpmMedia = 93, Valencia = 3 },
            new Faixa { Id = 149, Titulo = "Madrid Skyline", Artista = "Solar Beat", Genero = "Pop", Pais = "Espanha", Ano = 2024, BpmMedia = 118, Valencia = 5 },
            new Faixa { Id = 150, Titulo = "Barcelona Nights", Artista = "Costa Roja", Genero = "Eletronica", Pais = "Espanha", Ano = 2023, BpmMedia = 128, Valencia = 4 },
            new Faixa { Id = 151, Titulo = "Santiago Azul", Artista = "Cordilheira", Genero = "Rock", Pais = "Chile", Ano = 2018, BpmMedia = 136, Valencia = 2 },
            new Faixa { Id = 152, Titulo = "Pampas", Artista = "Horizonte Sul", Genero = "Folk", Pais = "Argentina", Ano = 2021, BpmMedia = 80, Valencia = 5 },
            new Faixa { Id = 153, Titulo = "Cidade Neon", Artista = "DJ Horizonte", Genero = "Eletronica", Pais = "Portugal", Ano = 2024, BpmMedia = 127, Valencia = 5 },
            new Faixa { Id = 154, Titulo = "Metrô Central", Artista = "Bass Brasil", Genero = "Eletronica", Pais = "Brasil", Ano = 2019, BpmMedia = 129, Valencia = 3 },
            new Faixa { Id = 155, Titulo = "Reggae Paulista", Artista = "Roots SP", Genero = "Reggae", Pais = "Brasil", Ano = 2018, BpmMedia = 79, Valencia = 4 },
            new Faixa { Id = 156, Titulo = "Jazz Mineiro", Artista = "Clube das Esquinas", Genero = "Jazz", Pais = "Brasil", Ano = 2024, BpmMedia = 68, Valencia = 5 },
            new Faixa { Id = 157, Titulo = "Blues da Serra", Artista = "Estrada 040", Genero = "Blues", Pais = "Brasil", Ano = 2022, BpmMedia = 72, Valencia = 2 },
            new Faixa { Id = 158, Titulo = "Country Pantaneiro", Artista = "Campo Livre", Genero = "Country", Pais = "Brasil", Ano = 2021, BpmMedia = 90, Valencia = 5 },
            new Faixa { Id = 159, Titulo = "Tokyo Boulevard", Artista = "Mika Wave", Genero = "Pop", Pais = "Japão", Ano = 2023, BpmMedia = 117, Valencia = 5 },
            new Faixa { Id = 160, Titulo = "Rio de Neon", Artista = "Circuito Sul", Genero = "Eletronica", Pais = "Brasil", Ano = 2025, BpmMedia = 131, Valencia = 4 },
            new Faixa { Id = 161, Titulo = "Tokyo After Hours", Artista = "Sora Quartet", Genero = "Jazz", Pais = "Japão", Ano = 2022, BpmMedia = 71, Valencia = 4 },
            new Faixa { Id = 162, Titulo = "Berlin Blue", Artista = "East Station", Genero = "Jazz", Pais = "Alemanha", Ano = 2018, BpmMedia = 69, Valencia = 3 },
            new Faixa { Id = 163, Titulo = "Lisboa em Sol", Artista = "Alfama Jazz Trio", Genero = "Jazz", Pais = "Portugal", Ano = 2024, BpmMedia = 74, Valencia = 5 },
            new Faixa { Id = 164, Titulo = "Black Forest Blues", Artista = "Rhine Road", Genero = "Blues", Pais = "Alemanha", Ano = 2015, BpmMedia = 72, Valencia = 2 },
            new Faixa { Id = 165, Titulo = "Midnight Osaka", Artista = "Blue Lanterns", Genero = "Blues", Pais = "Japão", Ano = 2021, BpmMedia = 75, Valencia = 3 },
            new Faixa { Id = 166, Titulo = "Cowboy do Oriente", Artista = "Sakura Riders", Genero = "Country", Pais = "Japão", Ano = 2023, BpmMedia = 87, Valencia = 5 },
            new Faixa { Id = 167, Titulo = "Campos do Sul", Artista = "Los Pampas", Genero = "Country", Pais = "Argentina", Ano = 2019, BpmMedia = 84, Valencia = 4 },
            new Faixa { Id = 168, Titulo = "Shibuya Flow", Artista = "MC Kaze", Genero = "Rap", Pais = "Japão", Ano = 2024, BpmMedia = 96, Valencia = 3 },
            new Faixa { Id = 169, Titulo = "Ciudad Rima", Artista = "MC Azteca", Genero = "Rap", Pais = "México", Ano = 2022, BpmMedia = 92, Valencia = 2 },
            new Faixa { Id = 170, Titulo = "Mexico Underground", Artista = "Fuego Norte", Genero = "Rock", Pais = "México", Ano = 2018, BpmMedia = 138, Valencia = 2 },
            new Faixa { Id = 171, Titulo = "Lisbon Rebels", Artista = "Atlantic Noise", Genero = "Rock", Pais = "Portugal", Ano = 2020, BpmMedia = 140, Valencia = 2 },
            new Faixa { Id = 172, Titulo = "Caminho dos Andes", Artista = "Lucia Torres", Genero = "MPB", Pais = "Argentina", Ano = 2023, BpmMedia = 90, Valencia = 5 },
            new Faixa { Id = 173, Titulo = "Cordilheira Azul", Artista = "Camila Rojas", Genero = "MPB", Pais = "Chile", Ano = 2021, BpmMedia = 88, Valencia = 4 },
            new Faixa { Id = 174, Titulo = "Velho Farol", Artista = "João Navegante", Genero = "Folk", Pais = "Portugal", Ano = 2017, BpmMedia = 79, Valencia = 4 },
            new Faixa { Id = 175, Titulo = "Bamboo Road", Artista = "Kenji Folk", Genero = "Folk", Pais = "Japão", Ano = 2020, BpmMedia = 77, Valencia = 5 },
            new Faixa { Id = 176, Titulo = "Cidade Colorida", Artista = "Los Neon", Genero = "Indie", Pais = "México", Ano = 2024, BpmMedia = 106, Valencia = 5 },
            new Faixa { Id = 177, Titulo = "Bogotá Skyline", Artista = "Calle Norte", Genero = "Indie", Pais = "Colômbia", Ano = 2022, BpmMedia = 104, Valencia = 4 },
            new Faixa { Id = 178, Titulo = "Buenos Aires Beat", Artista = "Digital Tango", Genero = "Eletronica", Pais = "Argentina", Ano = 2024, BpmMedia = 129, Valencia = 4 },
            new Faixa { Id = 179, Titulo = "Valparaíso Pulse", Artista = "Pacific Synth", Genero = "Eletronica", Pais = "Chile", Ano = 2023, BpmMedia = 126, Valencia = 3 },
            new Faixa { Id = 180, Titulo = "Bogotá Summer", Artista = "Luna Viva", Genero = "Pop", Pais = "Colômbia", Ano = 2025, BpmMedia = 118, Valencia = 5 },
            new Faixa { Id = 181, Titulo = "Rio Elétrico", Artista = "Cidade Sintética", Genero = "Eletronica", Pais = "Brasil", Ano = 2025, BpmMedia = 132, Valencia = 5 },
            new Faixa { Id = 182, Titulo = "Favela Beat", Artista = "DJ Horizonte", Genero = "Eletronica", Pais = "Brasil", Ano = 2021, BpmMedia = 127, Valencia = 3 },
            new Faixa { Id = 183, Titulo = "Madrugada Tropical", Artista = "Clube Neon", Genero = "Eletronica", Pais = "Brasil", Ano = 2022, BpmMedia = 124, Valencia = 4 },
            new Faixa { Id = 184, Titulo = "Soul Paulista", Artista = "Blue Vila", Genero = "Jazz", Pais = "Brasil", Ano = 2025, BpmMedia = 70, Valencia = 5 },
            new Faixa { Id = 185, Titulo = "Raízes do Sul", Artista = "Estrada Velha", Genero = "Country", Pais = "Brasil", Ano = 2024, BpmMedia = 89, Valencia = 5 },
            new Faixa { Id = 186, Titulo = "Roots da Bahia", Artista = "Ilha Verde", Genero = "Reggae", Pais = "Brasil", Ano = 2023, BpmMedia = 81, Valencia = 5 },
            new Faixa { Id = 187, Titulo = "Subsolo", Artista = "MC Prisma", Genero = "Rap", Pais = "Brasil", Ano = 2025, BpmMedia = 97, Valencia = 2 },
            new Faixa { Id = 188, Titulo = "Aurora Boreal", Artista = "Nordic Echo", Genero = "Pop", Pais = "Suécia", Ano = 2024, BpmMedia = 115, Valencia = 5 },
            new Faixa { Id = 189, Titulo = "Frozen Circuit", Artista = "Ice Pulse", Genero = "Eletronica", Pais = "Noruega", Ano = 2025, BpmMedia = 130, Valencia = 4 },
            new Faixa { Id = 190, Titulo = "Stone Castle", Artista = "Royal Line", Genero = "Rock", Pais = "Irlanda", Ano = 2019, BpmMedia = 142, Valencia = 2 },
            new Faixa { Id = 191, Titulo = "Mediterranean Sun", Artista = "Costa Blanca", Genero = "Pop", Pais = "Espanha", Ano = 2025, BpmMedia = 117, Valencia = 5 },
            new Faixa { Id = 192, Titulo = "Barcelona Flow", Artista = "MC Iberia", Genero = "Rap", Pais = "Espanha", Ano = 2024, BpmMedia = 95, Valencia = 3 },
            new Faixa { Id = 193, Titulo = "Olive Trees", Artista = "Terra Nova", Genero = "Folk", Pais = "Espanha", Ano = 2021, BpmMedia = 78, Valencia = 4 },
            new Faixa { Id = 194, Titulo = "Lisboa Lights", Artista = "Atlantic Pulse", Genero = "Eletronica", Pais = "Portugal", Ano = 2025, BpmMedia = 128, Valencia = 5 },
            new Faixa { Id = 195, Titulo = "Canadian Sunset", Artista = "Maple Avenue", Genero = "Country", Pais = "Canadá", Ano = 2022, BpmMedia = 85, Valencia = 4 },
            new Faixa { Id = 196, Titulo = "Northern Blues", Artista = "Cold River", Genero = "Blues", Pais = "Canadá", Ano = 2020, BpmMedia = 73, Valencia = 3 },
            new Faixa { Id = 197, Titulo = "Digital Andes", Artista = "Future Peaks", Genero = "Eletronica", Pais = "Peru", Ano = 2024, BpmMedia = 127, Valencia = 4 },
            new Faixa { Id = 198, Titulo = "Lima Nights", Artista = "Pacific Dreams", Genero = "Pop", Pais = "Peru", Ano = 2023, BpmMedia = 116, Valencia = 5 },
            new Faixa { Id = 199, Titulo = "Echoes of Cusco", Artista = "Mountain Folk", Genero = "Folk", Pais = "Peru", Ano = 2022, BpmMedia = 80, Valencia = 4 },
            new Faixa { Id = 200, Titulo = "Pacific Highway", Artista = "West Coast Riders", Genero = "Rock", Pais = "Austrália", Ano = 2021, BpmMedia = 144, Valencia = 2 },
            new Faixa { Id = 201, Titulo = "Kingston Lights", Artista = "Island Echo", Genero = "Pop", Pais = "Jamaica", Ano = 2023, BpmMedia = 116, Valencia = 5 },
            new Faixa { Id = 202, Titulo = "Noches de México", Artista = "Trio Azteca", Genero = "Jazz", Pais = "México", Ano = 2021, BpmMedia = 72, Valencia = 4 },
            new Faixa { Id = 203, Titulo = "Buenos Aires Blue", Artista = "Puerto Jazz", Genero = "Jazz", Pais = "Argentina", Ano = 2020, BpmMedia = 70, Valencia = 3 },
            new Faixa { Id = 204, Titulo = "Lisbon Blues", Artista = "Atlantic Road", Genero = "Blues", Pais = "Portugal", Ano = 2018, BpmMedia = 74, Valencia = 2 },
            new Faixa { Id = 205, Titulo = "Valley Blues", Artista = "Andes Smoke", Genero = "Blues", Pais = "Chile", Ano = 2022, BpmMedia = 73, Valencia = 3 },
            new Faixa { Id = 206, Titulo = "California Roots", Artista = "West Coast Vibes", Genero = "Reggae", Pais = "EUA", Ano = 2024, BpmMedia = 82, Valencia = 5 },
            new Faixa { Id = 207, Titulo = "Berlin Roots", Artista = "Green Dub", Genero = "Reggae", Pais = "Alemanha", Ano = 2021, BpmMedia = 80, Valencia = 4 },
            new Faixa { Id = 208, Titulo = "Tokyo Reggae", Artista = "Island Sakura", Genero = "Reggae", Pais = "Japão", Ano = 2025, BpmMedia = 81, Valencia = 5 },
            new Faixa { Id = 209, Titulo = "Country Road Berlin", Artista = "Black Forest Riders", Genero = "Country", Pais = "Alemanha", Ano = 2020, BpmMedia = 86, Valencia = 4 },
            new Faixa { Id = 210, Titulo = "Campos de Lisboa", Artista = "Atlantic Cowboys", Genero = "Country", Pais = "Portugal", Ano = 2022, BpmMedia = 85, Valencia = 4 },
            new Faixa { Id = 211, Titulo = "Rancho Azteca", Artista = "Los Vaqueros", Genero = "Country", Pais = "México", Ano = 2024, BpmMedia = 88, Valencia = 5 },
            new Faixa { Id = 212, Titulo = "Patagonia Dreams", Artista = "South Lights", Genero = "Indie", Pais = "Argentina", Ano = 2023, BpmMedia = 105, Valencia = 4 },
            new Faixa { Id = 213, Titulo = "Cordillera", Artista = "Pacific Noise", Genero = "Indie", Pais = "Chile", Ano = 2021, BpmMedia = 103, Valencia = 3 },
            new Faixa { Id = 214, Titulo = "Lima Skyline", Artista = "Miraflores", Genero = "Indie", Pais = "Peru", Ano = 2025, BpmMedia = 107, Valencia = 5 },
            new Faixa { Id = 215, Titulo = "Toronto Flow", Artista = "MC North", Genero = "Rap", Pais = "Canadá", Ano = 2022, BpmMedia = 94, Valencia = 3 },
            new Faixa { Id = 216, Titulo = "Sydney Rhymes", Artista = "MC Harbour", Genero = "Rap", Pais = "Austrália", Ano = 2024, BpmMedia = 95, Valencia = 2 },
            new Faixa { Id = 217, Titulo = "Samurai Rock", Artista = "Crimson Noise", Genero = "Rock", Pais = "Japão", Ano = 2019, BpmMedia = 141, Valencia = 2 },
            new Faixa { Id = 218, Titulo = "Céu Mexicano", Artista = "Isabela Luna", Genero = "MPB", Pais = "México", Ano = 2024, BpmMedia = 91, Valencia = 5 },
            new Faixa { Id = 219, Titulo = "Bogotá ao Entardecer", Artista = "Camila Sol", Genero = "MPB", Pais = "Colômbia", Ano = 2023, BpmMedia = 88, Valencia = 4 },
            new Faixa { Id = 220, Titulo = "Canção dos Andes", Artista = "Miguel Flores", Genero = "MPB", Pais = "Peru", Ano = 2022, BpmMedia = 89, Valencia = 5 },
            new Faixa { Id = 221, Titulo = "Electro Kingston", Artista = "Dub Circuit", Genero = "Eletronica", Pais = "Jamaica", Ano = 2025, BpmMedia = 129, Valencia = 5 },
            new Faixa { Id = 222, Titulo = "Neon Bogotá", Artista = "Digital Andes", Genero = "Eletronica", Pais = "Colômbia", Ano = 2024, BpmMedia = 128, Valencia = 4 },
            new Faixa { Id = 223, Titulo = "Osaka Sunrise", Artista = "Future Pulse", Genero = "Pop", Pais = "Japão", Ano = 2025, BpmMedia = 119, Valencia = 5 },
            new Faixa { Id = 224, Titulo = "Alpine Nights", Artista = "Helvetic Sound", Genero = "Eletronica", Pais = "Suíça", Ano = 2023, BpmMedia = 127, Valencia = 4 },
            new Faixa { Id = 225, Titulo = "Swiss Echo", Artista = "Crystal Peak", Genero = "Indie", Pais = "Suíça", Ano = 2022, BpmMedia = 104, Valencia = 4 },
            new Faixa { Id = 226, Titulo = "Vienna Jazz Club", Artista = "Blue Danube", Genero = "Jazz", Pais = "Áustria", Ano = 2021, BpmMedia = 71, Valencia = 4 },
            new Faixa { Id = 227, Titulo = "Alps Highway", Artista = "Mountain Riders", Genero = "Rock", Pais = "Suíça", Ano = 2020, BpmMedia = 139, Valencia = 2 },
            new Faixa { Id = 228, Titulo = "Vienna Lights", Artista = "Aurora Vienna", Genero = "Pop", Pais = "Áustria", Ano = 2024, BpmMedia = 117, Valencia = 5 },
            new Faixa { Id = 229, Titulo = "Dub Alps", Artista = "Green Mountain", Genero = "Reggae", Pais = "Suíça", Ano = 2025, BpmMedia = 80, Valencia = 5 },
            new Faixa { Id = 230, Titulo = "Vienna Flow", Artista = "MC Danube", Genero = "Rap", Pais = "Áustria", Ano = 2023, BpmMedia = 93, Valencia = 3 },
            new Faixa { Id = 231, Titulo = "Blue Alps", Artista = "Stone River", Genero = "Blues", Pais = "Suíça", Ano = 2019, BpmMedia = 74, Valencia = 3 },
            new Faixa { Id = 232, Titulo = "Forest Walk", Artista = "Helvetic Folk", Genero = "Folk", Pais = "Suíça", Ano = 2018, BpmMedia = 78, Valencia = 4 },
            new Faixa { Id = 233, Titulo = "Country Alps", Artista = "Snow Riders", Genero = "Country", Pais = "Suíça", Ano = 2021, BpmMedia = 86, Valencia = 4 },
            new Faixa { Id = 234, Titulo = "Alpine Melody", Artista = "Sofia Weiss", Genero = "MPB", Pais = "Suíça", Ano = 2025, BpmMedia = 90, Valencia = 5 },
            new Faixa { Id = 235, Titulo = "Aurora Digital", Artista = "Nord Pulse", Genero = "Eletronica", Pais = "Finlândia", Ano = 2024, BpmMedia = 130, Valencia = 4 },
            new Faixa { Id = 236, Titulo = "Northern Sky", Artista = "Ice Horizon", Genero = "Pop", Pais = "Finlândia", Ano = 2023, BpmMedia = 118, Valencia = 5 },
            new Faixa { Id = 237, Titulo = "Frozen Strings", Artista = "Arctic Folk", Genero = "Folk", Pais = "Finlândia", Ano = 2022, BpmMedia = 77, Valencia = 4 },
            new Faixa { Id = 238, Titulo = "Helsinki Underground", Artista = "Steel Pulse", Genero = "Rock", Pais = "Finlândia", Ano = 2021, BpmMedia = 140, Valencia = 2 },
            new Faixa { Id = 239, Titulo = "Midnight Snow", Artista = "Polar Quartet", Genero = "Jazz", Pais = "Finlândia", Ano = 2020, BpmMedia = 70, Valencia = 3 },
            new Faixa { Id = 240, Titulo = "Aurora Flow", Artista = "MC Polar", Genero = "Rap", Pais = "Finlândia", Ano = 2025, BpmMedia = 96, Valencia = 3 },
            new Faixa { Id = 241, Titulo = "Bogotá Blue", Artista = "Café Central", Genero = "Jazz", Pais = "Colômbia", Ano = 2022, BpmMedia = 72, Valencia = 4 },
            new Faixa { Id = 242, Titulo = "Valparaíso Jazz", Artista = "Pacific Quartet", Genero = "Jazz", Pais = "Chile", Ano = 2020, BpmMedia = 69, Valencia = 3 },
            new Faixa { Id = 243, Titulo = "Desert Blues", Artista = "Camino Azul", Genero = "Blues", Pais = "México", Ano = 2021, BpmMedia = 74, Valencia = 3 },
            new Faixa { Id = 244, Titulo = "Pampas Blues", Artista = "Smoke River", Genero = "Blues", Pais = "Argentina", Ano = 2019, BpmMedia = 73, Valencia = 2 },
            new Faixa { Id = 245, Titulo = "Campos do Pacífico", Artista = "Los Rancheros", Genero = "Country", Pais = "Chile", Ano = 2024, BpmMedia = 87, Valencia = 5 },
            new Faixa { Id = 246, Titulo = "Vale Sagrado", Artista = "Andes Country", Genero = "Country", Pais = "Peru", Ano = 2023, BpmMedia = 85, Valencia = 4 },
            new Faixa { Id = 247, Titulo = "Maple Roots", Artista = "North Vibes", Genero = "Reggae", Pais = "Canadá", Ano = 2022, BpmMedia = 81, Valencia = 5 },
            new Faixa { Id = 248, Titulo = "Coral Reef", Artista = "Sunny Dub", Genero = "Reggae", Pais = "Austrália", Ano = 2024, BpmMedia = 82, Valencia = 4 },
            new Faixa { Id = 249, Titulo = "Stockholm Flow", Artista = "MC Baltic", Genero = "Rap", Pais = "Suécia", Ano = 2025, BpmMedia = 95, Valencia = 3 },
            new Faixa { Id = 250, Titulo = "Oslo Streets", Artista = "MC Fjord", Genero = "Rap", Pais = "Noruega", Ano = 2023, BpmMedia = 94, Valencia = 2 },
            new Faixa { Id = 251, Titulo = "Costa Mediterrânea", Artista = "Helena Mar", Genero = "MPB", Pais = "Espanha", Ano = 2025, BpmMedia = 90, Valencia = 5 },
            new Faixa { Id = 252, Titulo = "Roma ao Entardecer", Artista = "Giulia Costa", Genero = "MPB", Pais = "Itália", Ano = 2024, BpmMedia = 89, Valencia = 5 },
            new Faixa { Id = 253, Titulo = "Montanhas Verdes", Artista = "Raízes Andinas", Genero = "Folk", Pais = "Colômbia", Ano = 2021, BpmMedia = 79, Valencia = 4 },
            new Faixa { Id = 254, Titulo = "Camino del Sol", Artista = "Los Vientos", Genero = "Folk", Pais = "México", Ano = 2020, BpmMedia = 80, Valencia = 4 },
            new Faixa { Id = 255, Titulo = "Atlantic Dreams", Artista = "Blue Lisbon", Genero = "Indie", Pais = "Portugal", Ano = 2022, BpmMedia = 106, Valencia = 5 },
            new Faixa { Id = 256, Titulo = "Berlin Nights", Artista = "Echo District", Genero = "Indie", Pais = "Alemanha", Ano = 2023, BpmMedia = 104, Valencia = 4 },
            new Faixa { Id = 257, Titulo = "Buenos Aires Pop", Artista = "Valentina Sol", Genero = "Pop", Pais = "Argentina", Ano = 2025, BpmMedia = 118, Valencia = 5 },
            new Faixa { Id = 258, Titulo = "Santiago Lights", Artista = "Luna Pacific", Genero = "Pop", Pais = "Chile", Ano = 2024, BpmMedia = 117, Valencia = 5 },
            new Faixa { Id = 259, Titulo = "Milano Pulse", Artista = "Digital Roma", Genero = "Eletronica", Pais = "Itália", Ano = 2025, BpmMedia = 128, Valencia = 4 },
            new Faixa { Id = 260, Titulo = "Roman Empire", Artista = "Iron Avenue", Genero = "Rock", Pais = "Itália", Ano = 2018, BpmMedia = 141, Valencia = 2 },
            new Faixa { Id = 261, Titulo = "Venice Sunset", Artista = "Laguna Pop", Genero = "Pop", Pais = "Itália", Ano = 2023, BpmMedia = 116, Valencia = 5 },
            new Faixa { Id = 262, Titulo = "Roma Groove", Artista = "Blue Tiber", Genero = "Jazz", Pais = "Itália", Ano = 2021, BpmMedia = 71, Valencia = 4 },
            new Faixa { Id = 263, Titulo = "Italian Roads", Artista = "Open Highway", Genero = "Country", Pais = "Itália", Ano = 2022, BpmMedia = 84, Valencia = 4 },
            new Faixa { Id = 264, Titulo = "Tuscan Wind", Artista = "Green Hills", Genero = "Folk", Pais = "Itália", Ano = 2020, BpmMedia = 78, Valencia = 5 },
            new Faixa { Id = 265, Titulo = "Dub Milano", Artista = "Roots Italia", Genero = "Reggae", Pais = "Itália", Ano = 2025, BpmMedia = 80, Valencia = 5 },
            new Faixa { Id = 266, Titulo = "MC Roma", Artista = "Capital Flow", Genero = "Rap", Pais = "Itália", Ano = 2024, BpmMedia = 96, Valencia = 3 },
            new Faixa { Id = 267, Titulo = "Blue Venice", Artista = "Canal Smoke", Genero = "Blues", Pais = "Itália", Ano = 2022, BpmMedia = 72, Valencia = 3 },
            new Faixa { Id = 268, Titulo = "Neon Alps", Artista = "Euro Synth", Genero = "Eletronica", Pais = "Áustria", Ano = 2025, BpmMedia = 129, Valencia = 5 },
            new Faixa { Id = 269, Titulo = "Danube Dreams", Artista = "Vienna Echo", Genero = "Indie", Pais = "Áustria", Ano = 2023, BpmMedia = 105, Valencia = 4 },
            new Faixa { Id = 270, Titulo = "Mountain Song", Artista = "Alpine Voices", Genero = "MPB", Pais = "Áustria", Ano = 2024, BpmMedia = 88, Valencia = 5 },
            new Faixa { Id = 271, Titulo = "Snow Roots", Artista = "Aurora Dub", Genero = "Reggae", Pais = "Finlândia", Ano = 2024, BpmMedia = 81, Valencia = 4 },
            new Faixa { Id = 272, Titulo = "Arctic Country", Artista = "Frozen Trail", Genero = "Country", Pais = "Finlândia", Ano = 2023, BpmMedia = 85, Valencia = 4 },
            new Faixa { Id = 273, Titulo = "Frozen Blues", Artista = "Ice River", Genero = "Blues", Pais = "Finlândia", Ano = 2021, BpmMedia = 73, Valencia = 3 },
            new Faixa { Id = 274, Titulo = "Northern Indie", Artista = "Polar Lights", Genero = "Indie", Pais = "Finlândia", Ano = 2025, BpmMedia = 106, Valencia = 5 },
            new Faixa { Id = 275, Titulo = "Aurora MPB", Artista = "Clara Boreal", Genero = "MPB", Pais = "Finlândia", Ano = 2024, BpmMedia = 90, Valencia = 5 },
            new Faixa { Id = 276, Titulo = "Forest Beat", Artista = "Nordic Pulse", Genero = "Eletronica", Pais = "Suécia", Ano = 2025, BpmMedia = 129, Valencia = 4 },
            new Faixa { Id = 277, Titulo = "Stockholm Sunset", Artista = "Sofia North", Genero = "Pop", Pais = "Suécia", Ano = 2025, BpmMedia = 118, Valencia = 5 },
            new Faixa { Id = 278, Titulo = "Swedish Roads", Artista = "North Riders", Genero = "Country", Pais = "Suécia", Ano = 2021, BpmMedia = 84, Valencia = 4 },
            new Faixa { Id = 279, Titulo = "Blue Fjord", Artista = "Oslo Trio", Genero = "Jazz", Pais = "Noruega", Ano = 2022, BpmMedia = 70, Valencia = 4 },
            new Faixa { Id = 280, Titulo = "Rock of Oslo", Artista = "Northern Storm", Genero = "Rock", Pais = "Noruega", Ano = 2020, BpmMedia = 142, Valencia = 2 },
            new Faixa { Id = 281, Titulo = "Copenhagen Blue", Artista = "Nordic Quartet", Genero = "Jazz", Pais = "Dinamarca", Ano = 2023, BpmMedia = 71, Valencia = 4 },
            new Faixa { Id = 282, Titulo = "Brussels Night", Artista = "Blue Avenue", Genero = "Jazz", Pais = "Bélgica", Ano = 2021, BpmMedia = 70, Valencia = 3 },
            new Faixa { Id = 283, Titulo = "Northern Whiskey", Artista = "Cold Harbor", Genero = "Blues", Pais = "Dinamarca", Ano = 2020, BpmMedia = 73, Valencia = 2 },
            new Faixa { Id = 284, Titulo = "Belgian Smoke", Artista = "Old Train Blues", Genero = "Blues", Pais = "Bélgica", Ano = 2022, BpmMedia = 74, Valencia = 3 },
            new Faixa { Id = 285, Titulo = "Warsaw Fire", Artista = "Eastern Steel", Genero = "Rock", Pais = "Polônia", Ano = 2024, BpmMedia = 142, Valencia = 2 },
            new Faixa { Id = 286, Titulo = "Prague Storm", Artista = "Iron Castle", Genero = "Rock", Pais = "República Tcheca", Ano = 2021, BpmMedia = 139, Valencia = 1 },
            new Faixa { Id = 287, Titulo = "Athens Circuit", Artista = "Digital Olympus", Genero = "Eletronica", Pais = "Grécia", Ano = 2025, BpmMedia = 130, Valencia = 5 },
            new Faixa { Id = 288, Titulo = "Istanbul Frequency", Artista = "Bosphorus Beat", Genero = "Eletronica", Pais = "Turquia", Ano = 2024, BpmMedia = 128, Valencia = 4 },
            new Faixa { Id = 289, Titulo = "Mumbai Lights", Artista = "Riya Nova", Genero = "Pop", Pais = "Índia", Ano = 2025, BpmMedia = 119, Valencia = 5 },
            new Faixa { Id = 290, Titulo = "Cape Sunset", Artista = "Golden Coast", Genero = "Pop", Pais = "África do Sul", Ano = 2023, BpmMedia = 117, Valencia = 5 },
            new Faixa { Id = 291, Titulo = "Mumbai Streets", Artista = "MC Bombay", Genero = "Rap", Pais = "Índia", Ano = 2024, BpmMedia = 96, Valencia = 3 },
            new Faixa { Id = 292, Titulo = "Johannesburg Flow", Artista = "Urban Gold", Genero = "Rap", Pais = "África do Sul", Ano = 2023, BpmMedia = 94, Valencia = 2 },
            new Faixa { Id = 293, Titulo = "Kiwi Valley", Artista = "Southern Roots", Genero = "Folk", Pais = "Nova Zelândia", Ano = 2022, BpmMedia = 79, Valencia = 4 },
            new Faixa { Id = 294, Titulo = "Greek Islands", Artista = "Blue Horizon", Genero = "Folk", Pais = "Grécia", Ano = 2021, BpmMedia = 78, Valencia = 5 },
            new Faixa { Id = 295, Titulo = "New Zealand Roads", Artista = "Pacific Riders", Genero = "Country", Pais = "Nova Zelândia", Ano = 2024, BpmMedia = 86, Valencia = 4 },
            new Faixa { Id = 296, Titulo = "Copenhagen Trails", Artista = "Northern Fields", Genero = "Country", Pais = "Dinamarca", Ano = 2022, BpmMedia = 85, Valencia = 4 },
            new Faixa { Id = 297, Titulo = "Island Dub", Artista = "Ocean Roots", Genero = "Reggae", Pais = "Nova Zelândia", Ano = 2025, BpmMedia = 82, Valencia = 5 },
            new Faixa { Id = 298, Titulo = "African Roots", Artista = "Cape Vibes", Genero = "Reggae", Pais = "África do Sul", Ano = 2024, BpmMedia = 80, Valencia = 5 },
            new Faixa { Id = 299, Titulo = "Bruxelas Tropical", Artista = "Luz Atlântica", Genero = "MPB", Pais = "Bélgica", Ano = 2025, BpmMedia = 89, Valencia = 4 },
            new Faixa { Id = 300, Titulo = "Istanbul Dreams", Artista = "Golden Street", Genero = "Indie", Pais = "Turquia", Ano = 2024, BpmMedia = 105, Valencia = 5 },
            new Faixa { Id = 301, Titulo = "Warsaw Echo", Artista = "Neon East", Genero = "Indie", Pais = "Polônia", Ano = 2023, BpmMedia = 104, Valencia = 4 },
            new Faixa { Id = 302, Titulo = "Prague Morning", Artista = "Old Bridge", Genero = "Folk", Pais = "República Tcheca", Ano = 2020, BpmMedia = 77, Valencia = 4 },
            new Faixa { Id = 303, Titulo = "Athens Sunset", Artista = "Mediterranean Flow", Genero = "Pop", Pais = "Grécia", Ano = 2025, BpmMedia = 116, Valencia = 5 },
            new Faixa { Id = 304, Titulo = "Ankara Streets", Artista = "Urban East", Genero = "Rap", Pais = "Turquia", Ano = 2024, BpmMedia = 95, Valencia = 3 },
            new Faixa { Id = 305, Titulo = "Istanbul Rock", Artista = "Black Sea", Genero = "Rock", Pais = "Turquia", Ano = 2022, BpmMedia = 141, Valencia = 2 },
            new Faixa { Id = 306, Titulo = "Delhi Pulse", Artista = "Future India", Genero = "Eletronica", Pais = "Índia", Ano = 2025, BpmMedia = 131, Valencia = 5 },
            new Faixa { Id = 307, Titulo = "Indian Roots", Artista = "River Song", Genero = "Folk", Pais = "Índia", Ano = 2023, BpmMedia = 78, Valencia = 4 },
            new Faixa { Id = 308, Titulo = "Mumbai Jazz", Artista = "Blue Palace", Genero = "Jazz", Pais = "Índia", Ano = 2022, BpmMedia = 72, Valencia = 3 },
            new Faixa { Id = 309, Titulo = "Cape Blues", Artista = "Southern Smoke", Genero = "Blues", Pais = "África do Sul", Ano = 2021, BpmMedia = 73, Valencia = 2 },
            new Faixa { Id = 310, Titulo = "Safari Groove", Artista = "Wild Rhythm", Genero = "Eletronica", Pais = "África do Sul", Ano = 2025, BpmMedia = 127, Valencia = 4 },
            new Faixa { Id = 311, Titulo = "Danish Pulse", Artista = "Copenhagen Digital", Genero = "Eletronica", Pais = "Dinamarca", Ano = 2024, BpmMedia = 129, Valencia = 4 },
            new Faixa { Id = 312, Titulo = "Belgian Night", Artista = "Brussels Wave", Genero = "Eletronica", Pais = "Bélgica", Ano = 2025, BpmMedia = 128, Valencia = 5 },
            new Faixa { Id = 313, Titulo = "Polish Horizon", Artista = "Eastern Lights", Genero = "Pop", Pais = "Polônia", Ano = 2024, BpmMedia = 117, Valencia = 5 },
            new Faixa { Id = 314, Titulo = "Czech Valley", Artista = "Bohemian Road", Genero = "Folk", Pais = "República Tcheca", Ano = 2022, BpmMedia = 79, Valencia = 4 },
            new Faixa { Id = 315, Titulo = "Greek Fire", Artista = "Olympus Rock", Genero = "Rock", Pais = "Grécia", Ano = 2023, BpmMedia = 143, Valencia = 2 },
            new Faixa { Id = 316, Titulo = "Turkish Blue", Artista = "Bosphorus Jazz", Genero = "Jazz", Pais = "Turquia", Ano = 2021, BpmMedia = 70, Valencia = 4 },
            new Faixa { Id = 317, Titulo = "Indian Ocean", Artista = "Mumbai Wave", Genero = "Indie", Pais = "Índia", Ano = 2024, BpmMedia = 106, Valencia = 5 },
            new Faixa { Id = 318, Titulo = "African Highway", Artista = "Cape Riders", Genero = "Country", Pais = "África do Sul", Ano = 2022, BpmMedia = 86, Valencia = 4 },
            new Faixa { Id = 319, Titulo = "Kiwi Lights", Artista = "Southern Sky", Genero = "Pop", Pais = "Nova Zelândia", Ano = 2025, BpmMedia = 118, Valencia = 5 },
            new Faixa { Id = 320, Titulo = "Pacific Dub", Artista = "Ocean Roots", Genero = "Reggae", Pais = "Nova Zelândia", Ano = 2024, BpmMedia = 81, Valencia = 5 },
            new Faixa { Id = 321, Titulo = "Seoul Midnight", Artista = "Han River Trio", Genero = "Jazz", Pais = "Coreia do Sul", Ano = 2023, BpmMedia = 70, Valencia = 3 },
            new Faixa { Id = 322, Titulo = "Digital Seoul", Artista = "K-Pulse", Genero = "Eletronica", Pais = "Coreia do Sul", Ano = 2025, BpmMedia = 132, Valencia = 5 },
            new Faixa { Id = 323, Titulo = "Steel Korea", Artista = "Red Machine", Genero = "Rock", Pais = "Coreia do Sul", Ano = 2021, BpmMedia = 145, Valencia = 1 },
            new Faixa { Id = 324, Titulo = "Neon Seoul", Artista = "Mina Sky", Genero = "Pop", Pais = "Coreia do Sul", Ano = 2024, BpmMedia = 119, Valencia = 5 },
            new Faixa { Id = 325, Titulo = "Seoul Streets", Artista = "MC Tiger", Genero = "Rap", Pais = "Coreia do Sul", Ano = 2022, BpmMedia = 96, Valencia = 2 },
            new Faixa { Id = 326, Titulo = "Han River Song", Artista = "Luna Park", Genero = "MPB", Pais = "Coreia do Sul", Ano = 2025, BpmMedia = 89, Valencia = 4 },
            new Faixa { Id = 327, Titulo = "Barcelona Blues", Artista = "Blue Madrid", Genero = "Blues", Pais = "Espanha", Ano = 2021, BpmMedia = 72, Valencia = 2 },
            new Faixa { Id = 328, Titulo = "Madrid Jazz Club", Artista = "Iberia Quartet", Genero = "Jazz", Pais = "Espanha", Ano = 2020, BpmMedia = 71, Valencia = 4 },
            new Faixa { Id = 329, Titulo = "Cancun Roots", Artista = "Mar Azul", Genero = "Reggae", Pais = "México", Ano = 2023, BpmMedia = 82, Valencia = 5 },
            new Faixa { Id = 330, Titulo = "Buenos Aires Roots", Artista = "Rio Verde", Genero = "Reggae", Pais = "Argentina", Ano = 2024, BpmMedia = 80, Valencia = 5 },
            new Faixa { Id = 331, Titulo = "Andes Highway", Artista = "Campo Livre", Genero = "Country", Pais = "Colômbia", Ano = 2022, BpmMedia = 86, Valencia = 4 },
            new Faixa { Id = 332, Titulo = "Tokyo Country Road", Artista = "Eastern Cowboys", Genero = "Country", Pais = "Japão", Ano = 2025, BpmMedia = 88, Valencia = 5 },
            new Faixa { Id = 333, Titulo = "Roma Alternative", Artista = "Velvet Streets", Genero = "Indie", Pais = "Itália", Ano = 2023, BpmMedia = 105, Valencia = 4 },
            new Faixa { Id = 334, Titulo = "Athens Dreams", Artista = "Blue Horizon", Genero = "Indie", Pais = "Grécia", Ano = 2022, BpmMedia = 103, Valencia = 5 },
            new Faixa { Id = 335, Titulo = "Ankara Fields", Artista = "East Valley", Genero = "Folk", Pais = "Turquia", Ano = 2021, BpmMedia = 78, Valencia = 4 },
            new Faixa { Id = 336, Titulo = "Brussels Forest", Artista = "Green Roads", Genero = "Folk", Pais = "Bélgica", Ano = 2024, BpmMedia = 80, Valencia = 5 },
            new Faixa { Id = 337, Titulo = "Mumbai Steel", Artista = "Dark Highway", Genero = "Rock", Pais = "Índia", Ano = 2023, BpmMedia = 147, Valencia = 1 },
            new Faixa { Id = 338, Titulo = "Lima Digital", Artista = "Future Andes", Genero = "Eletronica", Pais = "Peru", Ano = 2025, BpmMedia = 130, Valencia = 4 },
            new Faixa { Id = 339, Titulo = "Santiago Flow", Artista = "MC Andes", Genero = "Rap", Pais = "Chile", Ano = 2024, BpmMedia = 95, Valencia = 2 },
            new Faixa { Id = 340, Titulo = "Peru Sunset", Artista = "Sol Pacifico", Genero = "Pop", Pais = "Peru", Ano = 2023, BpmMedia = 117, Valencia = 5 },
            new Faixa { Id = 341, Titulo = "Oslo Circuit", Artista = "Northern Code", Genero = "Eletronica", Pais = "Noruega", Ano = 2025, BpmMedia = 133, Valencia = 4 },
            new Faixa { Id = 342, Titulo = "Fjord Lights", Artista = "Polar Dreams", Genero = "Pop", Pais = "Noruega", Ano = 2024, BpmMedia = 115, Valencia = 5 },
            new Faixa { Id = 343, Titulo = "Nordic Blues", Artista = "Frozen River", Genero = "Blues", Pais = "Noruega", Ano = 2022, BpmMedia = 73, Valencia = 2 },
            new Faixa { Id = 344, Titulo = "Fjord Country", Artista = "Mountain Riders", Genero = "Country", Pais = "Noruega", Ano = 2021, BpmMedia = 85, Valencia = 4 },
            new Faixa { Id = 345, Titulo = "Oslo Folk", Artista = "Northern Voice", Genero = "Folk", Pais = "Noruega", Ano = 2020, BpmMedia = 77, Valencia = 5 },
            new Faixa { Id = 346, Titulo = "Tokyo Rock Night", Artista = "Red Sakura", Genero = "Rock", Pais = "Japão", Ano = 2025, BpmMedia = 150, Valencia = 1 },
            new Faixa { Id = 347, Titulo = "Kyoto Indie", Artista = "Silent Garden", Genero = "Indie", Pais = "Japão", Ano = 2023, BpmMedia = 101, Valencia = 4 },
            new Faixa { Id = 348, Titulo = "Osaka Rap", Artista = "MC Zen", Genero = "Rap", Pais = "Japão", Ano = 2024, BpmMedia = 97, Valencia = 3 },
            new Faixa { Id = 349, Titulo = "Sakura Jazz", Artista = "Tokyo Blue", Genero = "Jazz", Pais = "Japão", Ano = 2022, BpmMedia = 69, Valencia = 4 },
            new Faixa { Id = 350, Titulo = "Kyoto Blues", Artista = "Silent Moon", Genero = "Blues", Pais = "Japão", Ano = 2021, BpmMedia = 72, Valencia = 2 },
            new Faixa { Id = 351, Titulo = "Berlin Night Drive", Artista = "Dark Frequency", Genero = "Eletronica", Pais = "Alemanha", Ano = 2025, BpmMedia = 134, Valencia = 2 },
            new Faixa { Id = 352, Titulo = "Hamburg Rock", Artista = "Steel Harbor", Genero = "Rock", Pais = "Alemanha", Ano = 2024, BpmMedia = 148, Valencia = 1 },
            new Faixa { Id = 353, Titulo = "Munich Jazz", Artista = "Blue Hall", Genero = "Jazz", Pais = "Alemanha", Ano = 2023, BpmMedia = 70, Valencia = 5 },
            new Faixa { Id = 354, Titulo = "German Roots", Artista = "Green Forest", Genero = "Folk", Pais = "Alemanha", Ano = 2022, BpmMedia = 79, Valencia = 4 },
            new Faixa { Id = 355, Titulo = "Berlin Pop", Artista = "City Lights", Genero = "Pop", Pais = "Alemanha", Ano = 2025, BpmMedia = 118, Valencia = 5 },
            new Faixa { Id = 356, Titulo = "Paris Rap", Artista = "MC Lumiere", Genero = "Rap", Pais = "França", Ano = 2024, BpmMedia = 96, Valencia = 2 },
            new Faixa { Id = 357, Titulo = "French Blues", Artista = "Blue Riviera", Genero = "Blues", Pais = "França", Ano = 2023, BpmMedia = 73, Valencia = 3 },
            new Faixa { Id = 358, Titulo = "French Country", Artista = "Rural Paris", Genero = "Country", Pais = "França", Ano = 2022, BpmMedia = 84, Valencia = 4 },
            new Faixa { Id = 359, Titulo = "Paris Folk", Artista = "Green Avenue", Genero = "Folk", Pais = "França", Ano = 2021, BpmMedia = 78, Valencia = 5 },
            new Faixa { Id = 360, Titulo = "French Indie", Artista = "Velvet Metro", Genero = "Indie", Pais = "França", Ano = 2025, BpmMedia = 106, Valencia = 4 },
            new Faixa { Id = 361, Titulo = "Cairo Midnight", Artista = "Nile Quartet", Genero = "Jazz", Pais = "Egito", Ano = 2022, BpmMedia = 68, Valencia = 3 },
            new Faixa { Id = 362, Titulo = "Desert Pulse", Artista = "Sahara Code", Genero = "Eletronica", Pais = "Egito", Ano = 2025, BpmMedia = 131, Valencia = 4 },
            new Faixa { Id = 363, Titulo = "Pharaoh Rock", Artista = "Golden Ankh", Genero = "Rock", Pais = "Egito", Ano = 2023, BpmMedia = 146, Valencia = 1 },
            new Faixa { Id = 364, Titulo = "Cairo Dreams", Artista = "Layla Moon", Genero = "Pop", Pais = "Egito", Ano = 2024, BpmMedia = 116, Valencia = 5 },
            new Faixa { Id = 365, Titulo = "Nile Stories", Artista = "River Voices", Genero = "Folk", Pais = "Egito", Ano = 2021, BpmMedia = 76, Valencia = 4 },
            new Faixa { Id = 366, Titulo = "Casablanca Blue", Artista = "Atlas Smoke", Genero = "Blues", Pais = "Marrocos", Ano = 2022, BpmMedia = 72, Valencia = 2 },
            new Faixa { Id = 367, Titulo = "Sahara Nights", Artista = "Morocco Wave", Genero = "Eletronica", Pais = "Marrocos", Ano = 2025, BpmMedia = 129, Valencia = 5 },
            new Faixa { Id = 368, Titulo = "Atlas Highway", Artista = "Desert Riders", Genero = "Country", Pais = "Marrocos", Ano = 2023, BpmMedia = 86, Valencia = 4 },
            new Faixa { Id = 369, Titulo = "Marrakech Flow", Artista = "MC Medina", Genero = "Rap", Pais = "Marrocos", Ano = 2024, BpmMedia = 95, Valencia = 2 },
            new Faixa { Id = 370, Titulo = "Red Sand Folk", Artista = "Atlas Roots", Genero = "Folk", Pais = "Marrocos", Ano = 2021, BpmMedia = 79, Valencia = 5 },
            new Faixa { Id = 371, Titulo = "Tel Aviv Lights", Artista = "Neon Desert", Genero = "Pop", Pais = "Israel", Ano = 2025, BpmMedia = 118, Valencia = 5 },
            new Faixa { Id = 372, Titulo = "Jerusalem Echo", Artista = "Old Stone", Genero = "Folk", Pais = "Israel", Ano = 2022, BpmMedia = 77, Valencia = 4 },
            new Faixa { Id = 373, Titulo = "Dead Sea Blues", Artista = "Salt River", Genero = "Blues", Pais = "Israel", Ano = 2023, BpmMedia = 71, Valencia = 2 },
            new Faixa { Id = 374, Titulo = "Tel Aviv Circuit", Artista = "Future Coast", Genero = "Eletronica", Pais = "Israel", Ano = 2024, BpmMedia = 133, Valencia = 4 },
            new Faixa { Id = 375, Titulo = "Negev Rock", Artista = "Stone Horizon", Genero = "Rock", Pais = "Israel", Ano = 2021, BpmMedia = 144, Valencia = 1 },
            new Faixa { Id = 376, Titulo = "Dubai Skyline", Artista = "Golden Future", Genero = "Eletronica", Pais = "Emirados Árabes", Ano = 2025, BpmMedia = 135, Valencia = 5 },
            new Faixa { Id = 377, Titulo = "Desert City", Artista = "Urban Mirage", Genero = "Pop", Pais = "Emirados Árabes", Ano = 2024, BpmMedia = 117, Valencia = 5 },
            new Faixa { Id = 378, Titulo = "Arabian Flow", Artista = "MC Oasis", Genero = "Rap", Pais = "Emirados Árabes", Ano = 2023, BpmMedia = 96, Valencia = 3 },
            new Faixa { Id = 379, Titulo = "Sand Roads", Artista = "Nomad Strings", Genero = "Folk", Pais = "Emirados Árabes", Ano = 2022, BpmMedia = 75, Valencia = 4 },
            new Faixa { Id = 380, Titulo = "Dubai Night Jazz", Artista = "Palm Quartet", Genero = "Jazz", Pais = "Emirados Árabes", Ano = 2021, BpmMedia = 69, Valencia = 3 },
            new Faixa { Id = 381, Titulo = "Bangkok Pulse", Artista = "Siam Digital", Genero = "Eletronica", Pais = "Tailândia", Ano = 2025, BpmMedia = 132, Valencia = 5 },
            new Faixa { Id = 382, Titulo = "Thai Sunset", Artista = "Golden Lotus", Genero = "Pop", Pais = "Tailândia", Ano = 2024, BpmMedia = 116, Valencia = 5 },
            new Faixa { Id = 383, Titulo = "Bangkok Streets", Artista = "MC Lotus", Genero = "Rap", Pais = "Tailândia", Ano = 2023, BpmMedia = 94, Valencia = 2 },
            new Faixa { Id = 384, Titulo = "Siam Blue", Artista = "River Smoke", Genero = "Blues", Pais = "Tailândia", Ano = 2022, BpmMedia = 72, Valencia = 3 },
            new Faixa { Id = 385, Titulo = "Thai Forest", Artista = "Lotus Roots", Genero = "Folk", Pais = "Tailândia", Ano = 2021, BpmMedia = 78, Valencia = 4 },
            new Faixa { Id = 386, Titulo = "Jakarta Night", Artista = "Island Circuit", Genero = "Eletronica", Pais = "Indonésia", Ano = 2025, BpmMedia = 130, Valencia = 4 },
            new Faixa { Id = 387, Titulo = "Bali Sunset", Artista = "Ocean Light", Genero = "Pop", Pais = "Indonésia", Ano = 2024, BpmMedia = 115, Valencia = 5 },
            new Faixa { Id = 388, Titulo = "Java Streets", Artista = "MC Island", Genero = "Rap", Pais = "Indonésia", Ano = 2023, BpmMedia = 97, Valencia = 2 },
            new Faixa { Id = 389, Titulo = "Volcano Rock", Artista = "Fire Island", Genero = "Rock", Pais = "Indonésia", Ano = 2022, BpmMedia = 149, Valencia = 1 },
            new Faixa { Id = 390, Titulo = "Bali Folk", Artista = "Green Islands", Genero = "Folk", Pais = "Indonésia", Ano = 2021, BpmMedia = 79, Valencia = 5 },
            new Faixa { Id = 391, Titulo = "Manila Lights", Artista = "Pacific Dreams", Genero = "Pop", Pais = "Filipinas", Ano = 2025, BpmMedia = 118, Valencia = 5 },
            new Faixa { Id = 392, Titulo = "Manila Underground", Artista = "Urban Waves", Genero = "Rap", Pais = "Filipinas", Ano = 2024, BpmMedia = 95, Valencia = 3 },
            new Faixa { Id = 393, Titulo = "Pacific Jazz", Artista = "Island Quartet", Genero = "Jazz", Pais = "Filipinas", Ano = 2022, BpmMedia = 70, Valencia = 4 },
            new Faixa { Id = 394, Titulo = "Tropical Circuit", Artista = "Future Manila", Genero = "Eletronica", Pais = "Filipinas", Ano = 2025, BpmMedia = 128, Valencia = 5 },
            new Faixa { Id = 395, Titulo = "Island Roots", Artista = "Ocean Folk", Genero = "Reggae", Pais = "Filipinas", Ano = 2023, BpmMedia = 82, Valencia = 5 },
            new Faixa { Id = 396, Titulo = "Havana Nights", Artista = "Caribbean Pulse", Genero = "Jazz", Pais = "Cuba", Ano = 2022, BpmMedia = 74, Valencia = 5 },
            new Faixa { Id = 397, Titulo = "Cuba Digital", Artista = "Tropical Code", Genero = "Eletronica", Pais = "Cuba", Ano = 2024, BpmMedia = 126, Valencia = 4 },
            new Faixa { Id = 398, Titulo = "Havana Streets", Artista = "MC Caribe", Genero = "Rap", Pais = "Cuba", Ano = 2023, BpmMedia = 93, Valencia = 3 },
            new Faixa { Id = 399, Titulo = "Caribbean Rock", Artista = "Blue Island", Genero = "Rock", Pais = "Cuba", Ano = 2021, BpmMedia = 143, Valencia = 2 },
            new Faixa { Id = 400, Titulo = "Island Sunset", Artista = "Cuban Roots", Genero = "Folk", Pais = "Cuba", Ano = 2020, BpmMedia = 78, Valencia = 5 },
        };
    }
}
